Revert "Convert diagrams from Mscgen and Graphviz to Mermaid (#154)"
I can't get mermaid to work properly on Github Runner.
Revert to old diagrams until further notice.

Reported error:

   Error: Could not find Chromium (rev. 1108766)

This reverts commit 0a8252d2b31e08debb82835f8b95653b4f9f5767.